// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * BrowserService provides browser selection functionality
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as browsers$0 from "./internal/browsers/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as preferences$0 from "./internal/preferences/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as updater$0 from "./internal/updater/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";

/**
 * CheckForUpdates checks if a new version is available
 */
export function CheckForUpdates(): $CancellablePromise<updater$0.UpdateInfo | null> {
    return $Call.ByID(2676099596);
}

/**
 * ClosePreferences hides the preferences window
 */
export function ClosePreferences(): $CancellablePromise<void> {
    return $Call.ByID(2219185419);
}

/**
 * GetAppVersion returns the current application version
 */
export function GetAppVersion(): $CancellablePromise<string> {
    return $Call.ByID(2027000098);
}

/**
 * GetPreferences returns the current preferences
 */
export function GetPreferences(): $CancellablePromise<preferences$0.Preferences | null> {
    return $Call.ByID(2519719495);
}

/**
 * GetURL returns the current URL
 */
export function GetURL(): $CancellablePromise<string> {
    return $Call.ByID(1395777516);
}

/**
 * HideWindow hides the chooser window
 */
export function HideWindow(): $CancellablePromise<void> {
    return $Call.ByID(153888081);
}

/**
 * ListAllBrowsers returns all detected browsers without filtering
 */
export function ListAllBrowsers(): $CancellablePromise<browsers$0.Browser[] | null> {
    return $Call.ByID(2941775469);
}

/**
 * ListBrowsers returns all detected browsers filtered by preferences
 */
export function ListBrowsers(): $CancellablePromise<browsers$0.Browser[] | null> {
    return $Call.ByID(442339540);
}

/**
 * Open opens the selected browser with the URL
 */
export function Open(request: browsers$0.OpenRequest): $CancellablePromise<void> {
    return $Call.ByID(1368667045, request);
}

/**
 * OpenPreferences shows the preferences window
 */
export function OpenPreferences(): $CancellablePromise<void> {
    return $Call.ByID(857493501);
}

/**
 * Quit quits the application
 */
export function Quit(): $CancellablePromise<void> {
    return $Call.ByID(4170750314);
}

/**
 * Resize resizes the chooser window
 */
export function Resize(width: number, height: number): $CancellablePromise<void> {
    return $Call.ByID(3864607029, width, height);
}

/**
 * SavePreferences saves the preferences to disk
 */
export function SavePreferences(prefs: preferences$0.Preferences | null): $CancellablePromise<void> {
    return $Call.ByID(3126479662, prefs);
}

/**
 * SetURL sets a new URL and emits the url-changed event
 * The frontend will show the window when ready
 */
export function SetURL(newURL: string): $CancellablePromise<void> {
    return $Call.ByID(3223555592, newURL);
}

/**
 * SetWindows sets references to the app windows
 */
export function SetWindows(chooser: application$0.WebviewWindow | null, prefs: application$0.WebviewWindow | null): $CancellablePromise<void> {
    return $Call.ByID(2413789908, chooser, prefs);
}

/**
 * ShowWindow shows and centers the chooser window
 */
export function ShowWindow(): $CancellablePromise<void> {
    return $Call.ByID(1795396284);
}
