// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface Browser {
    "type": string;
    "name": string;
    "profiles": Profile[] | null;
    "icon": string;

    /**
     * Whether to show the main browser entry (without profile)
     */
    "showMainEntry": boolean;
}

export interface OpenRequest {
    "browser": string;
    "profile": string;
    "type": string;
}

export interface Profile {
    "name": string;
    "directory": string;
    "icon": string;
}
