// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * UpdateInfo contains information about an available update
 */
export interface UpdateInfo {
    "Available": boolean;
    "Version": string;
    "ReleaseNotes": string;
    "DownloadURL": string;
    "CurrentVersion": string;
}
