// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Preferences stores user preferences for the application
 */
export interface Preferences {
    /**
     * Browser name + profile name (e.g., "Google Chrome:Work")
     */
    "defaultBrowser": string;

    /**
     * Map of browser+profile combinations to hide
     */
    "hiddenBrowsers": { [_ in string]?: boolean } | null;

    /**
     * If true, always open with default without showing UI
     */
    "alwaysUseDefault": boolean;
}
